[[links]]
target = "~/rsm-test/target_dir/hyprland.conf"
source = "~/rsm-test/dotfiles/configs/hyprland.conf"
tags = ["wm", "ui"]
os = "linux"

[[links]]
target = "~/rsm-test/target_dir/bashrc"
source = "~/rsm-test/dotfiles/configs/bashrc"
tags = ["shell"]

[[links]]
target = "~/rsm-test/target_dir/zshrc"
source = "~/rsm-test/dotfiles/configs/zshrc"
tags = ["shell", "work"]
